### ISSUE TITLE
Cannot build sample source

### ISSUE THREAD

**Issue by manfredlotz** [vbmithr/ocaml-smtp#4]
Hi there,
I installed smpt 0.3 via opam. Then tried to compile test/test_unix.ml and got an error:

$ ocamlbuild -pkg smtp_unix  test_unix.native
ocamlfind: Package `smtp_unix' not found
Cannot run Ocamlfind.

Any idea what I'm doing wrong? Thanks.

**Comment by vbmithr** [comment]
You need to do `ocamlbuild -pkg smtp.unix test_unix.native`

**Comment by manfredlotz** [comment]
Thanks a lot. That does it indeed.

I'm asking myself how I could have discovered it on my own?

**Comment by vbmithr** [comment]
On 05/11/2016 22:08, manfredlotz wrote:

> I'm asking myself how I could have discovered it by my own?

Check out pkg/META, it describe the packages as seen by ocamlfind.

Subpackages are always separated by `.`

## 

Vincent
